Traceback (most recent call last):
  File "/projects/ps-yeolab3/s5xu/eclip-qc/jupyter_testing/find.py", line 126, in <module>
    result = get_esummary(esearch_string=esearch_string, db='nucleotide')
  File "/projects/ps-yeolab3/s5xu/eclip-qc/jupyter_testing/find.py", line 55, in get_esummary
    response = urllib.request.urlopen(url)
  File "/home/s5xu/anaconda3/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/home/s5xu/anaconda3/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/home/s5xu/anaconda3/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/home/s5xu/anaconda3/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/home/s5xu/anaconda3/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/home/s5xu/anaconda3/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error
